### ISSUE TITLE
REQUEST - Wiring

### ISSUE THREAD

**Issue by redfirebrooks** [bostrt/attiny85-oled-rtc#1]
Hello,
could you please explain how to wire DS1306 and SSD1306 on the Attiny85 ?

**Comment by bostrt** [comment]
Certainly! Both modules use I2C which is super easy to wire up.

Here's a diagram of the attiny85:

![attiny85-pinout](https://user-images.githubusercontent.com/215290/42115826-a20c3f26-7bc2-11e8-9504-d2677fc640c2.png)

DS1307 | attiny85
------------|------------
GND | GND
5V | VCC
SDA | Pin 5 (SDA)
SCL | Pin 7 (SCL)
SQW | XXX

SSD1306 | attiny85
-------------|------------
GND | GND
VCC | VCC
SDA | Pin 5 (SDA)
SCL | Pin 7 (SCL)

Here's a bad picture of them hooked up, took this a long time ago when my wire organization wasn't very good...

![img_20170915_134651226](https://user-images.githubusercontent.com/215290/42116017-7ac4c78e-7bc3-11e8-9156-df7bcb240661.jpg)

**Comment by bostrt** [comment]
@redfirebrooks I'm closing this issue now but feel free to reopen if you need some more detail!

**Comment by redfirebrooks** [comment]
Thanks a lot !!!


Frédéric
Envoyé de mon iPhone
